import { supabase } from '../lib/supabase';

export const courseService = {
  /** List all courses the user teaches (instructor) or is enrolled in (student) */
  async listMyCourses() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { data: null, error: 'Not authenticated' };

    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single();

    if (profile?.role === 'instructor') {
      return supabase
        .from('courses')
        .select('*, course_enrollments(count)')
        .eq('instructor_id', user.id)
        .order('created_at', { ascending: false });
    } else {
      // Query courses where course_enrollments has student_id = user.id
      const { data, error } = await supabase
        .from('course_enrollments')
        .select('course_id, courses(*)')
        .eq('student_id', user.id);

      if (error) return { data: null, error: error.message };
      const courses = data.map(item => item.courses).filter(Boolean);
      return { data: courses, error: null };
    }
  },

  /** Create a new course — join code is auto-generated by DB trigger */
  async create(title: string, description: string, semester: string) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { data: null, error: 'Not authenticated' };

    return supabase
      .from('courses')
      .insert({ instructor_id: user.id, title, description, semester })
      .select()
      .single();
  },

  /** Get full course details including roster */
  async getCourseWithRoster(courseId: string) {
    const { data, error } = await supabase
      .from('courses')
      .select(`
        *,
        course_enrollments(
          student_id,
          joined_at,
          student:student_id(
            id,
            full_name,
            email,
            avatar_url
          )
        )
      `)
      .eq('id', courseId)
      .single();

    if (error) return { data: null, error: error.message };

    // Format profiles
    const formattedRoster = data.course_enrollments.map((enr: any) => ({
      student_id: enr.student_id,
      joined_at: enr.joined_at,
      full_name: enr.student?.full_name || 'Enrolled Student',
      email: enr.student?.email || '',
      avatar_url: enr.student?.avatar_url
    }));

    return {
      data: {
        ...data,
        roster: formattedRoster
      },
      error: null
    };
  },

  /** Remove a student from a course roster */
  async removeStudent(courseId: string, studentId: string) {
    return supabase
      .from('course_enrollments')
      .delete()
      .eq('course_id', courseId)
      .eq('student_id', studentId);
  },

  /** Get per-assignment completion stats for the instructor dashboard */
  async getAssignmentStats(courseId: string, assignmentId: string) {
    const { data, error } = await supabase
      .from('submissions')
      .select(`
        id,
        student_id,
        total_score,
        grading_status,
        submitted_at,
        is_late,
        grade_report,
        manual_score,
        student:student_id(
          full_name,
          email
        )
      `)
      .eq('course_id', courseId)
      .eq('assignment_id', assignmentId);

    if (error) return { data: null, error: error.message };

    // Group by student to find their best/last attempt
    // Here we take the highest score attempt for each student
    const studentBestSubmissions: Record<string, typeof data[number]> = {};
    for (const sub of data) {
      const existing = studentBestSubmissions[sub.student_id];
      const currentScore = sub.manual_score !== null ? Number(sub.manual_score) : (sub.total_score !== null ? Number(sub.total_score) : 0);
      const existingScore = existing ? (existing.manual_score !== null ? Number(existing.manual_score) : (existing.total_score !== null ? Number(existing.total_score) : 0)) : -1;
      
      if (!existing || currentScore > existingScore) {
        studentBestSubmissions[sub.student_id] = sub;
      }
    }

    const bestSubs = Object.values(studentBestSubmissions);
    const graded = bestSubs.filter(s => s.grading_status === 'graded');
    const scores = graded.map(s => s.manual_score !== null ? Number(s.manual_score) : (s.total_score !== null ? Number(s.total_score) : 0));
    const passing = scores.filter(s => s >= 60).length;

    // Identify which test cases are failing most
    const testFailureCounts: Record<string, number> = {};
    for (const sub of graded) {
      const report = sub.grade_report as any;
      if (report?.testResults) {
        for (const tc of report.testResults) {
          if (!tc.passed) {
            testFailureCounts[tc.name] = (testFailureCounts[tc.name] ?? 0) + 1;
          }
        }
      }
    }

    // Sort failed checks
    const topFailingTestCases = Object.entries(testFailureCounts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([name, failCount]) => ({
        name,
        failCount,
        pct: graded.length > 0 ? (failCount / graded.length) * 100 : 0
      }));

    return {
      data: {
        totalEnrolled: bestSubs.length,
        submitted: bestSubs.length,
        passRate: graded.length > 0 ? (passing / graded.length) * 100 : 0,
        avgScore: scores.length > 0 ? scores.reduce((a, b) => a + b) / scores.length : 0,
        minScore: scores.length > 0 ? Math.min(...scores) : 0,
        maxScore: scores.length > 0 ? Math.max(...scores) : 0,
        topFailingTestCases,
        submissions: data,
      },
      error: null,
    };
  },
};

export const assignmentService = {
  /** Get all assignments for a course */
  async getCourseAssignments(courseId: string) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];
    
    // Check if user is instructor for this course
    const { data: course } = await supabase
      .from('courses')
      .select('instructor_id')
      .eq('id', courseId)
      .single();

    if (course?.instructor_id === user.id) {
      // Query raw table to get hidden_test_cases
      const { data } = await supabase
        .from('assignments')
        .select('*')
        .eq('course_id', courseId)
        .order('created_at', { ascending: true });
      return data || [];
    } else {
      // Query student view
      const { data } = await supabase
        .from('assignments_student_view')
        .select('*')
        .eq('course_id', courseId)
        .order('created_at', { ascending: true });
      return data || [];
    }
  },

  /** Get details of a single assignment */
  async getAssignment(assignmentId: string) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;

    // Check if user is instructor
    const { data: assign } = await supabase
      .from('assignments')
      .select('instructor_id')
      .eq('id', assignmentId)
      .single();

    if (assign?.instructor_id === user.id) {
      const { data } = await supabase
        .from('assignments')
        .select('*')
        .eq('id', assignmentId)
        .single();
      return data;
    } else {
      const { data } = await supabase
        .from('assignments_student_view')
        .select('*')
        .eq('id', assignmentId)
        .single();
      return data;
    }
  },

  /** Create a course assignment */
  async create(params: {
    courseId: string;
    title: string;
    description: string;
    difficulty: string;
    starterCode: string;
    blockedInstructions: string[];
    visibleTestCases: any[];
    hiddenTestCases: any[];
    rubricCorrectness: number;
    rubricEfficiency: number;
    rubricStyle: number;
    dueDate: string | null;
    latePenaltyPct: number;
    maxAttempts: number;
    maxCyclesLimit: number;
  }) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { data: null, error: 'Not authenticated' };

    return supabase
      .from('assignments')
      .insert({
        course_id: params.courseId,
        instructor_id: user.id,
        title: params.title,
        description: params.description,
        difficulty: params.difficulty,
        starter_code: params.starterCode,
        blocked_instructions: params.blockedInstructions,
        visible_test_cases: params.visibleTestCases,
        hidden_test_cases: params.hiddenTestCases,
        rubric_correctness: params.rubricCorrectness,
        rubric_efficiency: params.rubricEfficiency,
        rubric_style: params.rubricStyle,
        due_at: params.dueDate,
        late_penalty_pct: params.latePenaltyPct,
        max_attempts: params.maxAttempts,
        max_cycles_limit: params.maxCyclesLimit
      })
      .select()
      .single();
  },

  /** Update an assignment */
  async update(assignmentId: string, params: {
    title: string;
    description: string;
    difficulty: string;
    starterCode: string;
    blockedInstructions: string[];
    visibleTestCases: any[];
    hiddenTestCases: any[];
    rubricCorrectness: number;
    rubricEfficiency: number;
    rubricStyle: number;
    dueDate: string | null;
    latePenaltyPct: number;
    maxAttempts: number;
    maxCyclesLimit: number;
  }) {
    return supabase
      .from('assignments')
      .update({
        title: params.title,
        description: params.description,
        difficulty: params.difficulty,
        starter_code: params.starterCode,
        blocked_instructions: params.blockedInstructions,
        visible_test_cases: params.visibleTestCases,
        hidden_test_cases: params.hiddenTestCases,
        rubric_correctness: params.rubricCorrectness,
        rubric_efficiency: params.rubricEfficiency,
        rubric_style: params.rubricStyle,
        due_at: params.dueDate,
        late_penalty_pct: params.latePenaltyPct,
        max_attempts: params.maxAttempts,
        max_cycles_limit: params.maxCyclesLimit,
        updated_at: new Date().toISOString()
      })
      .eq('id', assignmentId)
      .select()
      .single();
  },

  /** Delete an assignment */
  async delete(assignmentId: string) {
    return supabase
      .from('assignments')
      .delete()
      .eq('id', assignmentId);
  }
};
