/**
 * Pipeline State Exporters — Feature #14
 * Export the current pipeline state as a Logisim circuit (.circ) or Verilog testbench (.v).
 */

import type { ParsedInstruction } from './mipsParser';
import type { EngineStats } from './pipelineEngine';
import { REG_NAMES } from './mipsParser';
import { encodeInstruction } from './encoder';

// ── Logisim Export ───────────────────────────────────────────────────────

export function exportToLogisim(
  instructions: ParsedInstruction[],
  registers: Int32Array,
  memory: Map<number, number>,
  stats: EngineStats,
): string {
  const memEntries = Array.from(memory.entries())
    .sort(([a], [b]) => a - b)
    .slice(0, 256); // Limit memory for manageable file

  const instrHex = instructions.map((inst, i) => {
    // Simple encoding for Logisim ROM
    const addr = i * 4;
    return `addr/${addr.toString(16).padStart(8, '0')} ${encodeInstruction(inst).hex.replace('0x', '')}`;
  });

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project source="3.8.0" version="1.0">
<!-- 
  MIPS Pipeline Simulator Export
  Generated by Architecture Simulator
  Instructions: ${instructions.length}
  Registers modified: ${countModifiedRegs(registers)}
  Stats: CPI=${stats.totalCycles > 0 && stats.instructionsCompleted > 0 ? (stats.totalCycles / stats.instructionsCompleted).toFixed(2) : 'N/A'}, Stalls=${stats.stallCycles}
-->

<lib desc="#Wiring" name="0"/>
<lib desc="#Gates" name="1"/>
<lib desc="#Memory" name="4"/>

<main name="MIPS_Pipeline"/>

<circuit name="MIPS_Pipeline">
  <a name="circuit" val="MIPS_Pipeline"/>
  <a name="clabel" val="MIPS 5-Stage Pipeline"/>
  <a name="clabelup" val="east"/>

  <!-- ════════════════════════════════════════════════════
       Instruction Memory (ROM)
       ════════════════════════════════════════════════════ -->
  <comp lib="4" name="ROM">
    <a name="addrWidth" val="10"/>
    <a name="dataWidth" val="32"/>
    <a name="label" val="Instruction Memory"/>
    <a name="contents">
${instrHex.join('\n')}
    </a>
  </comp>

  <!-- ════════════════════════════════════════════════════
       Register File
       ════════════════════════════════════════════════════ -->
  <comp lib="4" name="RAM">
    <a name="addrWidth" val="5"/>
    <a name="dataWidth" val="32"/>
    <a name="label" val="Register File"/>
    <a name="contents">
${Array.from({ length: 32 }, (_, i) =>
  `addr/${i.toString(16).padStart(2, '0')} ${(registers[i] >>> 0).toString(16).padStart(8, '0')} # ${REG_NAMES[i]}`
).join('\n')}
    </a>
  </comp>

  <!-- ════════════════════════════════════════════════════
       Data Memory
       ════════════════════════════════════════════════════ -->
  <comp lib="4" name="RAM">
    <a name="addrWidth" val="16"/>
    <a name="dataWidth" val="8"/>
    <a name="label" val="Data Memory"/>
    <a name="contents">
${memEntries.map(([addr, val]) =>
  `addr/${(addr & 0xFFFF).toString(16).padStart(4, '0')} ${val.toString(16).padStart(2, '0')}`
).join('\n')}
    </a>
  </comp>

  <!-- ════════════════════════════════════════════════════
       Pipeline Stage Labels
       ════════════════════════════════════════════════════ -->
  <!-- IF → ID → EX → MEM → WB -->

</circuit>
</project>
`;
}

// ── Verilog Testbench Export ──────────────────────────────────────────────

export function exportToVerilog(
  instructions: ParsedInstruction[],
  registers: Int32Array,
  memory: Map<number, number>,
  stats: EngineStats,
  forwardingEnabled: boolean,
): string {
  const regInits = Array.from({ length: 32 }, (_, i) =>
    `    registers[${i.toString().padStart(2)}] = 32'h${(registers[i] >>> 0).toString(16).padStart(8, '0')}; // ${REG_NAMES[i]}`
  ).join('\n');

  const instrComments = instructions.map((inst, i) =>
    `    // [${(i * 4).toString(16).padStart(4, '0')}] ${inst.raw.trim()}`
  ).join('\n');

  const memInits = Array.from(memory.entries())
    .sort(([a], [b]) => a - b)
    .slice(0, 128)
    .map(([addr, val]) =>
      `    data_memory[16'h${(addr & 0xFFFF).toString(16).padStart(4, '0')}] = 8'h${val.toString(16).padStart(2, '0')};`
    ).join('\n');

  return `// ═══════════════════════════════════════════════════════════════════
// MIPS Pipeline Testbench — Auto-generated by Architecture Simulator
// ═══════════════════════════════════════════════════════════════════
//
// Configuration:
//   Forwarding: ${forwardingEnabled ? 'ENABLED' : 'DISABLED'}
//   Instructions: ${instructions.length}
//   Expected Cycles: ${stats.totalCycles}
//   Expected CPI: ${stats.instructionsCompleted > 0 ? (stats.totalCycles / stats.instructionsCompleted).toFixed(2) : 'N/A'}
//   Stall Cycles: ${stats.stallCycles}
//   Forward Count: ${stats.forwardCount}
//   Branch Mispredictions: ${stats.branchMispredictions}
// ═══════════════════════════════════════════════════════════════════

\`timescale 1ns / 1ps

module mips_pipeline_tb;

  // ── Clock and Reset ────────────────────────────────────────────
  reg clk;
  reg rst_n;

  always #5 clk = ~clk; // 100 MHz clock

  // ── DUT ────────────────────────────────────────────────────────
  // Instantiate your MIPS pipeline here:
  // mips_pipeline dut (
  //   .clk(clk),
  //   .rst_n(rst_n),
  //   .pc(pc),
  //   .instruction(instruction),
  //   ...
  // );

  // ── Memory Models ──────────────────────────────────────────────
  reg [31:0] registers [0:31];
  reg [7:0]  data_memory [0:65535];
  reg [31:0] instruction_memory [0:${instructions.length - 1}];

  // ── Program Instructions ───────────────────────────────────────
${instrComments}

  // ── Expected Register State ────────────────────────────────────
  task init_expected_registers;
    begin
${regInits}
    end
  endtask

  // ── Expected Memory State ──────────────────────────────────────
  task init_expected_memory;
    begin
${memInits}
    end
  endtask

  // ── Verification ───────────────────────────────────────────────
  integer i;
  integer errors;

  task verify_registers;
    begin
      errors = 0;
      for (i = 0; i < 32; i = i + 1) begin
        // Compare DUT registers with expected
        // if (dut.reg_file[i] !== registers[i]) begin
        //   $display("ERROR: Register %0d mismatch. Expected: %h, Got: %h",
        //            i, registers[i], dut.reg_file[i]);
        //   errors = errors + 1;
        // end
      end
      if (errors == 0)
        $display("✓ All registers match expected values");
      else
        $display("✗ %0d register mismatches found", errors);
    end
  endtask

  // ── Cycle Counter ──────────────────────────────────────────────
  integer cycle_count;
  
  task verify_performance;
    begin
      $display("═══════════════════════════════════════════════");
      $display("Performance Verification:");
      $display("  Expected cycles: ${stats.totalCycles}");
      $display("  Actual cycles:   %0d", cycle_count);
      $display("  Expected stalls: ${stats.stallCycles}");
      $display("  Expected CPI:    ${stats.instructionsCompleted > 0 ? (stats.totalCycles / stats.instructionsCompleted).toFixed(2) : 'N/A'}");
      $display("═══════════════════════════════════════════════");
    end
  endtask

  // ── Main Test ──────────────────────────────────────────────────
  initial begin
    $dumpfile("mips_pipeline_tb.vcd");
    $dumpvars(0, mips_pipeline_tb);

    clk = 0;
    rst_n = 0;
    cycle_count = 0;

    // Reset
    #20 rst_n = 1;

    // Run for expected number of cycles + margin
    repeat (${stats.totalCycles + 20}) begin
      @(posedge clk);
      cycle_count = cycle_count + 1;
    end

    // Verify
    init_expected_registers;
    init_expected_memory;
    verify_registers;
    verify_performance;

    $display("\\n✓ Testbench complete");
    $finish;
  end

endmodule
`;
}

// ── Helpers ──────────────────────────────────────────────────────────────

function countModifiedRegs(registers: Int32Array): number {
  let count = 0;
  for (let i = 1; i < 32; i++) {
    if (registers[i] !== 0) count++;
  }
  // Exclude $gp (28) and $sp (29) which are initialized to non-zero
  if (registers[28] === 0x10008000) count--;
  if (registers[29] === 0x7FFFFFFC) count--;
  return Math.max(0, count);
}
