/**
 * MIPS Syscall Handler
 * Implements standard MIPS syscall services with I/O callback system.
 * Designed to work with both interactive (browser) and headless (autograder) modes.
 */

// ── Types ────────────────────────────────────────────────────────────────

export interface SyscallIO {
  /** Called when the program prints text */
  onPrint: (text: string) => void;
  /** Called when the program needs integer input. Returns a promise that resolves with the input. */
  onReadInt: () => Promise<number>;
  /** Called when the program needs string input. Returns a promise with the string. */
  onReadString: (maxLen: number) => Promise<string>;
  /** Called when the program exits (syscall 10) */
  onExit: () => void;
}

export interface SyscallResult {
  /** If true, the program should terminate */
  exit: boolean;
  /** If true, the engine should pause and wait for async input */
  waitForInput: boolean;
  /** Register values to write after syscall completes */
  registerWrites: Map<number, number>;
  /** Output text generated by this syscall */
  outputText: string;
}

// ── Syscall Numbers ──────────────────────────────────────────────────────

export const SYSCALL = {
  PRINT_INT: 1,
  PRINT_FLOAT: 2,
  PRINT_DOUBLE: 3,
  PRINT_STRING: 4,
  READ_INT: 5,
  READ_FLOAT: 6,
  READ_DOUBLE: 7,
  READ_STRING: 8,
  SBRK: 9,
  EXIT: 10,
  PRINT_CHAR: 11,
  READ_CHAR: 12,
  EXIT2: 17,
  PRINT_HEX: 34,
  EXIT_RISCV: 93,
} as const;

// ── Default IO (silent / headless) ───────────────────────────────────────

export const SILENT_IO: SyscallIO = {
  onPrint: () => {},
  onReadInt: () => Promise.resolve(0),
  onReadString: () => Promise.resolve(''),
  onExit: () => {},
};

// ── Handler ──────────────────────────────────────────────────────────────

/**
 * Execute a syscall based on $v0 value.
 * Reads registers and memory as needed, returns actions to perform.
 */
export function handleSyscall(
  v0: number,
  registers: Int32Array,
  memory: Map<number, number>,
): SyscallResult {
  const result: SyscallResult = {
    exit: false,
    waitForInput: false,
    registerWrites: new Map(),
    outputText: '',
  };

  switch (v0) {
    case SYSCALL.PRINT_INT: {
      // Print integer in $a0
      result.outputText = String(registers[4]); // $a0
      break;
    }

    case SYSCALL.PRINT_STRING: {
      // Print null-terminated string starting at address in $a0
      const addr = registers[4]; // $a0
      const bytes: number[] = [];
      let pos = addr;
      const maxLen = 4096; // Safety limit
      for (let i = 0; i < maxLen; i++) {
        const byte = memory.get(pos) ?? 0;
        if (byte === 0) break;
        bytes.push(byte);
        pos++;
      }
      const decoder = new TextDecoder('utf-8');
      result.outputText = decoder.decode(new Uint8Array(bytes));
      break;
    }

    case SYSCALL.READ_INT: {
      // Request integer input → result goes to $v0
      result.waitForInput = true;
      break;
    }

    case SYSCALL.READ_STRING: {
      // Read string into buffer at $a0, max length $a1
      result.waitForInput = true;
      break;
    }

    case SYSCALL.EXIT:
    case SYSCALL.EXIT2:
    case SYSCALL.EXIT_RISCV: {
      // Exit
      result.exit = true;
      break;
    }

    case SYSCALL.PRINT_CHAR: {
      // Print char in $a0
      const charCode = registers[4] & 0xFF; // $a0
      result.outputText = String.fromCharCode(charCode);
      break;
    }

    case SYSCALL.READ_CHAR: {
      // Request single char input → result goes to $v0
      result.waitForInput = true;
      break;
    }

    case SYSCALL.PRINT_HEX: {
      // Print $a0 as hex
      const val = registers[4] >>> 0; // $a0 as unsigned
      result.outputText = '0x' + val.toString(16).toUpperCase().padStart(8, '0');
      break;
    }

    case SYSCALL.SBRK: {
      // Allocate $a0 bytes on heap — simplified: just return current heap pointer
      // For now, return a fixed heap address. Full heap management is future work.
      result.registerWrites.set(2, 0x10040000); // $v0 = heap address
      break;
    }

    default: {
      result.outputText = `[Unknown syscall: ${v0}]\n`;
      break;
    }
  }

  return result;
}

/**
 * Complete a pending input syscall by writing the input value to the appropriate register/memory.
 */
export function completeSyscallInput(
  v0: number,
  inputValue: number | string,
  registers: Int32Array,
  memory: Map<number, number>,
): Map<number, number> {
  const writes = new Map<number, number>();

  switch (v0) {
    case SYSCALL.READ_INT: {
      // Write integer to $v0
      const val = typeof inputValue === 'number' ? inputValue : parseInt(String(inputValue), 10) || 0;
      writes.set(2, val); // $v0 = register 2
      break;
    }

    case SYSCALL.READ_CHAR: {
      // Write char to $v0
      const ch = typeof inputValue === 'string' ? inputValue.charCodeAt(0) : inputValue;
      writes.set(2, ch & 0xFF); // $v0 = register 2
      break;
    }

    case SYSCALL.READ_STRING: {
      // Write string to buffer at $a0, max length $a1
      const addr = registers[4]; // $a0
      const maxLen = registers[5]; // $a1
      const str = String(inputValue);
      const encoder = new TextEncoder();
      const bytes = encoder.encode(str);
      const len = Math.min(bytes.length, maxLen - 1); // Leave room for null terminator
      for (let i = 0; i < len; i++) {
        memory.set(addr + i, bytes[i]);
      }
      memory.set(addr + len, 0); // null terminator
      break;
    }
  }

  return writes;
}
